In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,])
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)

In [3]:
a

array([1, 2, 3])

In [8]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
arr = np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [12]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr = np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,2,3)
arr

array([1. , 1.5, 2. ])

In [17]:
arr = np.random.randint(20,50,10)
arr

array([32, 44, 41, 25, 26, 41, 26, 23, 36, 39])

In [27]:
ta = np.arange(5)
ta

array([0, 1, 2, 3, 4])

In [28]:
ta

array([0, 1, 2, 3, 4])

In [32]:
a

array([1, 2, 3])

In [36]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

---

---

# Inspecting Numpy Arrays

In [23]:
a.shape

(3,)

In [29]:
b.shape

(2, 3)

In [39]:
len(b)

2

In [31]:
len(a)

3

In [40]:
b.ndim

2

In [41]:
a.ndim

1

In [42]:
b.size

6

In [43]:
b.dtype

dtype('float64')

In [45]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

 # Manipulating Numpy Arrays 

In [47]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [48]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [52]:
np.delete(b,[1,1])

array([1.5, 3. , 4. , 5. , 6. ])

In [54]:
b.reshape(3,2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [55]:
np.append(a,b)

array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ])

# Numpy statistical Operations


In [58]:
a

array([1, 2, 3])

In [59]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [60]:
a.sum()

6

In [61]:
b.max()

6.0

In [63]:
b.min()

1.5

In [65]:
b.mean()

3.5833333333333335

In [66]:
np.median(b)

3.5

In [67]:
np.std(b)

1.5920810978785667

---------

--------
--------

-----------------------------
-------------------------------
------
-----
------



------------
--------

# Pandas Data Structures

In [88]:
import pandas as pd
import numpy as np

# Pandas Series

In [70]:
s = pd.Series([3,-5,7,4], index = ['a', 'b', 'c', 'd'])
s

a    3
b   -5
c    7
d    4
dtype: int64

In [74]:
l01 = np.random.randint(-10, 11, size = 8)

In [75]:
l01

array([ 10, -10,  -5,   4,  -1,  -3,   2,   8])

In [84]:
s01 = pd.Series(20, index = np.arange(0,9))
s01

0    20
1    20
2    20
3    20
4    20
5    20
6    20
7    20
8    20
dtype: int64

# DataFrame Pandas 

In [120]:
 data = {
    'Country': ['United States', 'United Kingdom', 'Canada'],
    'Capital': ['Washington', 'London', 'Ottawa'],
    'Population': [331002651, 67886011, 37894799]}
    
df = pd.DataFrame(data,columns=['Country', 'Capital', 'Population'])
df

Country     Capital  Population
0   United States  Washington   331002651
1  United Kingdom      London    67886011
2          Canada      Ottawa    37894799

# Pandas File I/O

In [121]:
ls

 Volume in drive C is Windows
 Volume Serial Number is F4EE-2B18

 Directory of C:\Users\soufiane\Documents\python data science\Youtube Mustapha othman

07/03/2023  12:53 AM    <DIR>          .
07/03/2023  12:53 AM    <DIR>          ..
07/02/2023  01:13 PM    <DIR>          .ipynb_checkpoints
07/03/2023  12:53 AM            25,449 car_financing.csv
07/03/2023  12:53 AM            30,036 car_financing.xlsx
07/02/2023  01:08 PM             4,674 Crash course.ipynb
07/03/2023  12:35 AM            21,521 NUMPY.ipynb
               4 File(s)         81,680 bytes
               3 Dir(s)  75,103,694,848 bytes free


In [122]:
df = pd.read_csv('car_financing.csv')
df

Month  Starting Balance  Repayment  Interest Paid  Principal Paid  \
0        1          34689.96     687.23         202.93          484.30   
1        2          34205.66     687.23         200.10          487.13   
2        3          33718.53     687.23         197.25          489.98   
3        4          33228.55     687.23         194.38          492.85   
4        5          32735.70     687.23         191.50          495.73   
..     ...               ...        ...            ...             ...   
403     56           3951.11     796.01           9.54          786.47   
404     57           3164.64     796.01           7.64          788.37   
405     58           2376.27     796.01           5.74          790.27   
406     59           1586.00     796.01           3.83          792.18   
407     60            793.82     796.01           1.91          794.10   

     New Balance  term  interest_rate       car_type  
0       34205.66    60         0.0702  Toyota Sienna  
1       33718.53    60         0.0702  Toyota Sienna  
2       33228.55    60         0.0702  Toyota Sienna  
3       32735.70    60         0.0702  Toyota Sienna  
4       32239.97    60         0.0702  Toyota Sienna  
..           ...   ...            ...            ...  
403      3164.64    60         0.0290      VW Golf R  
404      2376.27    60         0.0290      VW Golf R  
405      1586.00    60         0.0290      VW Golf R  
406       793.82    60         0.0290      VW Golf R  
407        -0.28    60         0.0290      VW Golf R  

[408 rows x 9 columns]

---
---
---
---
----
----
----

#  Pandas Information

In [126]:
git clone https://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@github.com/Sofenos/Jupyter.git
    

SyntaxError: invalid syntax (2287540947.py, line 1)